- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber #CD addition
  - Aspid
  - Cluster #CD map
  - Bagel
  - Box
  - Fland
  - Gemini
  - Marathon
  - Oasis
  - Omega #CD addition
  - Packed
  - Plasma
  - Reach
  - Ferrous
  # - Exo # CD Derotate
  - Snowball
  - Trieste
  #- Train <- return after station anchoring PR is finished and merged
  # Harmony maps start
  - Aspid
  - Atlas
  - Barratry
  - Elkridge
  - Jellyfish
  - Mira
  - Omega
  - Prime
  - Scylla
  - Wapiti
  - Amber
  # Harmony maps end
